### ISSUE TITLE
iOS App Content Loading issue

### ISSUE THREAD

**Issue by Narwat** [moodleuulm/moodle-local_boostnavigation#109]
Hi there, 
I am facing some issues in Moodle Mobile App, the iOS app is not loading the course content. When we click on a course, the app goes in indefinite waiting when we click of any course, there is some issue to get the content from server, but the course content is loading in android perfectly. Please suggest how to resolve this issue, I am attaching a screenshot of the issue.

Thanks in Advance

![screenshot-loading-content-issue](https://user-images.githubusercontent.com/96515249/147049658-300a2a72-edce-4cf1-9af7-97ed63854bc2.png)

Regards
Ranveer

**Comment by abias** [comment]
Hi @Narwat ,

this plugin does not have any Moodle-app-specific code and I am really wondering how / why this plugin could cause the Moodle app issue which you described.

Thus, please test if that problem of yours really goes away as soon as you uninstall the plugin. 
If it does go away, please leave another message here so that the issue can be investigated.
If it does not go away, I would like to ask you to check other possible causes within your system.

Cheers,
Alex
