### ISSUE TITLE
increment nodecounter even if node hidden

### ISSUE THREAD

**Issue by danmarsden** [moodleuulm/moodle-local_boostnavigation#24]
Hey Alex, 

Just wondering if it might be possible to increment the node count even when a node is hidden?
https://github.com/moodleuulm/moodle-local_boostnavigation/blob/6d1dda4f40ff61843d4a728aff47f00892d1307c/locallib.php#L218

We might have 4 links like:
* Page 1
* Page 2
* Page 3
* Page 4

We want to target all "Page 3" items with some slightly different css, but "Page 3" is only shown to a certain group of users. so when it's hidden the data-key on this is moved to the "Page 4"

Using some css like:
```
.list-group .list-group-item[data-key="localboostnavigationcustomrootusers3"] {
```

Does that make sense? - do you see any issues with it?

**Comment by abias** [comment]
Hi Dan,

you are absolutely right, incrementing the custom node ID attribute is not suitable anymore for the plethora of usergroup filters this plugin has in the meantime for custom nodes. However, I am afraid that if I change this behaviour now, I would have to introduce an admin setting for it or I would risk to break backwards compatibility for anybody who already relies on the ID attributes in his particular setup.

That's why I went ahead and created just one more node parameter for the node ID on https://github.com/moodleuulm/moodle-local_boostnavigation/commit/01b162722f3890b8e8ac11c8e7336387f1dcf6c1. As always, this parameter is optional and will survive even restructurings of the custom node tree by the admin. I think that it will be exactly what you are looking for in your scenario. If not, please let me know :)

Cheers,
Alex

**Comment by danmarsden** [comment]
nice solution - thanks!
