### ISSUE TITLE
Can I change the menu display

### ISSUE THREAD

**Issue by syusanjun** [moodleuulm/moodle-local_boostnavigation#30]
Can I change the menu display language by lang switching?

**Comment by abias** [comment]
Hi @syusanjun ,

as I don't fully understand what you are trying to achieve, can you please elaborate on your question?

Thanks,
Alex

**Comment by syusanjun** [comment]
I want to make sure that the language menu is displayed in the correct language when switching between Japanese and English.

The features available on moodle's appearance were not available.

grades, grades | /grade/report/mygrades.php | grades

**Comment by abias** [comment]
Hi @syusanjun ,

I have to admit that I still don't understand your problem and additionally I don't even know if your request is related to this problem.

Please take the time to write steps to reproduce (see https://docs.moodle.org/36/en/How_to_add_steps_to_reproduce_to_a_bug_report#Example_of_test_steps how to do this) so that I can handle this issue.

**Comment by abias** [comment]
Closing this issue for now as there hasn't been any answer anymore.
