### ISSUE TITLE
Competencies displayed in course settings menu

### ISSUE THREAD

**Issue by sarahjcotton** [moodleuulm/moodle-local_boostnavigation#38]
When the option to hide competencies from course nodes is selected, a link to competencies shows up in the settings menu. With boostnavigation disabled the link goes away again, so it would seem this is connected somehow.

Also, thank you for this plugin, it's superb!

![competencies](https://user-images.githubusercontent.com/2684004/58624405-0cb88480-82c8-11e9-863e-5d7bc5f68de2.JPG)

**Comment by abias** [comment]
Hi Sarah,

if you look at the "local_boostnavigation | removecompetenciescoursenode" setting of the plugin, you will read:

> Enabling this setting will remove the "Competencies" node from Boost's nav drawer if there are no competencies in the course. For teachers, there will be another "Competencies" node added to the course menu (cog menu).

So, yes, this node in the cog menu is added by local_boostnavigation by purpose. Otherwise, teachers would not be able to access competencies in their course anymore after removing the node from the nav drawer.

However, looking at your screenshot, I see that the new competencies node does not have an icon but it should have one.
This is fixed now on https://github.com/moodleuulm/moodle-local_boostnavigation/commit/a835fceb5ddc88a65d977dcf5090e89c49f6f7eb.

I am closing this issue now. If you have any more questions, please let me know.

Cheers,
Alex
