### ISSUE TITLE
No sections node in Moodle 3.7.1

### ISSUE THREAD

**Issue by ralf-krause** [moodleuulm/moodle-local_boostnavigation#43]
Hi,
in Moodle 3.7.1 I can't get a sections node in a course. All sections are listed and it is not possible to collapse and hide them. In Moodle 3.6.5 everything is okay.
Ralf

**Comment by rolandsherwood2** [comment]
Same problem here (reproduced under a fresh installation of Moodle 3.7.1 stable with version 2019061601 of the plugin). To clarify: the settings under _Course nodes > Insert course nodes to Boost's nav drawer_ and the settings under _Collapse course nodes in Boost's nav drawer_ appear to have no effect i.e. no sections are added and no collapsing functionality is offered.

**Comment by abias** [comment]
Hi @ralf-krause and hi @rolandsherwood2,

I am really sorry for this flaw and for my late reply. This bug sneaked in when we refactored the language pack in v3.7. As a result, the section node and activities node could not be checked / unchecked anymore in new and existing installations. 

It is now fixed in https://github.com/moodleuulm/moodle-local_boostnavigation/commit/9e0d8ca5c5a3179b6756be12786e16644c958b86.

I will publish a new version to the Moodle plugin repo soon, after some other issues have been processed.

Thanks,
Alex
