### ISSUE TITLE
Error on call function type(), if "Log in as" in course-context

### ISSUE THREAD

**Issue by adpe** [moodleuulm/moodle-local_boostnavigation#44]
Hello @abias 

We've following problem on our platform. If a manager is accessing a user profile within the course `https://FQDN/user/view.php?id=XXX&course=XXX`  to `Log in as` another user following error is displayed:

![image](https://user-images.githubusercontent.com/9467708/61778575-49ec4f00-adff-11e9-91eb-b412c50d6046.png)

But in the background you're logged in as the other student. And the error is only displayed, if `manager` is _not assigned_ in system-context. We've assigned the manager on a course-category context. So the solution is, to assign the role system-wide in the meantime.

I'll have a look to your code and provide a solution if I fixed it.

Greets,
Adrian

**Comment by adpe** [comment]
New important information! 

The error will be only displayed like reported above if the course is `hidden`. When the course is `visible` all is working like it should. But the error is thrown when the course is `hidden` and the permissions are set like mentioned above.

**Comment by abias** [comment]
Hi Adrian,

I thought I understood your problem and tried to examine your problem today, but I have to admit that I was not able to reproduce it locally. It seems to be a rare combination of edge cases.

Could you please give me a full set of steps to reproduce, based on a plain installation of Moodle 3.7?

Otherwise, please give an update if you were already able to examine this problem further and to create a patch.

Thanks,
Alex

**Comment by abias** [comment]
Hi @adpe ,

do you have any additional news for me about this issue?

Thanks,
Alex

**Comment by adpe** [comment]
Hello @abias 

I was on holidays and nobody takes it over on our end. I'll have a look to this issue during this day.

Greets,
Adrian

**Comment by abias** [comment]
Thank you, @adpe , for providing an updated pull request. I will have a look at it within or shortly before our 3.8 release.

Thanks,
Alex
