### ISSUE TITLE
 Customizing Nav Drawer in Boos

### ISSUE THREAD

**Issue by apinango70** [moodleuulm/moodle-local_boostnavigation#5]
Hi Alexander, I wonder if I could add at nav drawer links to resources and activities in Topics like a subtopic, Each topic will be a hierarchy level, i.e. a custom Topic could have subtopics with activities and/or resources own. Is this possible in Boost theme? 

I'm using your plugin **local_boostnavigation**, but if a made a menu, it appear at the end of the all block, not between the topics where the activities or resorces are. And this new menu will be in all courses.

I'm using moodle 3.4 

Best regards.

NOTE: I'm apologize about my bad english.

![pantalla2](https://user-images.githubusercontent.com/36819641/36643712-59abf334-1a2e-11e8-8675-a02f6a6b5559.png)

**Comment by abias** [comment]
Hi apinango70,

thank you for your feature proposal.

Originally, it's up to Moodle core and its course formats to add the section nodes to the navigation menu. In legacy themes like theme_clean, there may be additionally nodes in the navigation which link to the individual activities, if I remember correctly. However, Boost's goal is to have a clean and short menu in the nav drawer and that's why you only get nodes linking to the course sections.

Additionally, our plugin just adds an additional heading node to the list of sections (if configured) and lets you collapse the section nodes.

Technically, your goal could be implemented with the same mechanisms which local_boostnaviation is using. But I have to say that adding additional nodes like the ones you are requesting is clearly out of scope of local_boostnavigation and the time we can spend on the plugin as well as out of scope of the goals of the Boost nav drawer.

Sorry,
Alex.
