### ISSUE TITLE
when installing plugin for some reason i can't see my courses in manage courses and catagories

### ISSUE THREAD

**Issue by Melly78** [moodleuulm/moodle-local_boostnavigation#55]
I have been trying to edit and change the nav drawer options to take out calender, badges, and other nodes in the nav drawer to simplify navigation for Tradies that get confused and just press and inspect and confuses the use of it. 

i have added in some css code and also installed this plugin and with both attempts the being able to access and view the courses in the manage course categories completely disappears
see attached screen shot. Any thoughts or comments would greatly help
[When CSS is in theme CSS style sheets and plugin.docx](https://github.com/moodleuulm/moodle-local_boostnavigation/files/4141854/When.CSS.is.in.theme.CSS.style.sheets.and.plugin.docx)

**Comment by abias** [comment]
Hi @Melly78 ,

I am unsure what to do with this issue here.

I can't support any custom CSS code which you are using to modify your navigation.
I also won't open the attached word document for security reasons.

If you have request / issue with local_boostnavigation functionality, please separate it from any CSS stuff and let me clearly know how I can help. Please also attach any screenshots directly to this issue instead of packaging it into a docx.

Cheers,
Alex
