### ISSUE TITLE
[Improvement proposal] Enhance localization of "for {$a->who}" and "to {$a->who}"

### ISSUE THREAD

**Issue by izendegi** [moodleuulm/moodle-local_boostnavigation#56]
While localizing this plugin to Basque I've detected that it uses the {$a->who} parameter on different contexts ("_for {$a->who}_" and "_to {$a->who}_").

That is a problem on some languages like in Basque, because we add different suffixes to the noun when declining "for users" and "to users" that are also different according to the last letter of the noun:
- _user**s**_ --> erabiltzaile**ak**
- _**for** users_ --> erabiltzaile**entzat**
- _**to** users_ --> erabiltzaile**ei**

I've figured out a temporary workaround by setting inc_customwhoadmins and inc_customwhousers without any suffix and adding them on the strings that uses the {$a->who} parameter according to that context, but this works only because in Basque those two strings by coincidence end with the same letter and therefore the suffix is the same for both of them. If at any time in the future you add another figure used in {$a->who} it may stop working.

A possible solution may be creating strings for each combination of roles and declination (at this it would be the 3 combinations shown above for "all users" and another 3 for "admins")

**Comment by abias** [comment]
Hi @izendegi ,

thank you for translating our plugin and for pointing me to this problem in Basque!

I finally had the time to have a look at the problem which you have raised and I understand your solution proposal.

However, I just see the string setting_insertcustomnodes_desc as the only one who uses the `to {$a->who}` substring. And I didn't find a single string which uses the `{$a->who}` placeholder without a preceding `for`. That's why - and just looking at the changes which would be necessary in the english language pack - your solution proposal seems slightly overkill to me.

As an alternative approach, could you please tell me if it would help if I would just change the string setting_insertcustomnodes_desc from 
`With this setting, you can insert {$a->what} to Boost's nav drawer which will be added {$a->where} and which will be shown to {$a->who}.`
to something like
`With this setting, you can insert {$a->what} to Boost's nav drawer which will be added {$a->where} and which will be visible for {$a->who}.`
?

Thanks,
Alex

**Comment by izendegi** [comment]
Hi Alex,

I agree, adding strings would be quite overkill because the workaround works for now.

Thanks!
