### ISSUE TITLE
Onclik event

### ISSUE THREAD

**Issue by teseo24** [moodleuulm/moodle-local_boostnavigation#74]
Hi,

I put this code into insertcustomnodesadmins Documentos Normativos | $URL " onclick="window.open('$URL', '', 'width=620,height=450,toolbar=no,location=no,menubar=no,copyhistory=no,status=no,directories=no,scrollbars=yes,resizable=yes,left=200, top=50'); return false;

This requirement is for my customer. Is a really a  nice plugin

Is working but it opens twice, I dont what happen. Can you send me what is the event related in order to check it?

Thank in advance

**Comment by abias** [comment]
Hi @teseo24 ,

what you are trying to do here should be considered as hack and is not covered by the scope of this plugin at all. You should have also noticed in the settings of this plugin that there is a note that opening a custom link within a new tab is technically impossible.

The only thing I can say is:
As you add the URL to the custom node _and_ add an onclick event which will open the URL in a popup window, it is obvious that the page is opened twice - once in the main window and once as popup.

You can try to set the URL of the node to "#" so that only the onclick event opens the popup.

I think that's all I can say about that and I can also say that I don't see a chance to include a feature to open popups with local_boostnavigation.

I hope you understand.

Cheers,
Alex
